name: day_60_morning_challenge
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com



#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
